import React from 'react';
import {
  Moon,
  Users,
  Eye,
  HeartPulse,
  Crosshair,
  Sparkles,
  Shield,
  Heart,
  EyeOff,
  Laugh,
  Crown,
  Fingerprint,
  Flame,
  Biohazard,
  Hammer,
  PawPrint,
  Copy,
  Swords,
  Skull,
  VolumeX,
  VenetianMask,
  Baby,
  Gavel,
  ShieldAlert,
  Brain,
} from 'lucide-react';
import { Role, Team } from './game.js';

export interface RoleConfigMeta {
  role: Role;
  name: string;
  team: Team;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  badgeClass: string;
  description: string;
}

export const ALL_ROLES_META: RoleConfigMeta[] = [
  {
    role: 'WEREWOLF',
    name: 'Werewolf',
    team: 'WEREWOLVES',
    icon: Moon,
    color: 'text-rose-600 dark:text-rose-400',
    badgeClass: 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
    description: 'Each night, agree with your pack to hunt and eliminate a villager.',
  },
  {
    role: 'VILLAGER',
    name: 'Villager',
    team: 'VILLAGERS',
    icon: Users,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
    description: 'Use your sharp wits, deduction, and vote to ferret out the wolves before sunset.',
  },
  {
    role: 'SEER',
    name: 'Seer',
    team: 'VILLAGERS',
    icon: Eye,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
    description: 'Each night, choose one player to peer into their soul and learn their true nature.',
  },
  {
    role: 'DOCTOR',
    name: 'Doctor',
    team: 'VILLAGERS',
    icon: HeartPulse,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
    description: 'Each night, choose one player to protect from werewolf assault.',
  },
  {
    role: 'HUNTER',
    name: 'Hunter',
    team: 'VILLAGERS',
    icon: Crosshair,
    color: 'text-amber-600 dark:text-amber-400',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
    description: 'If you are slain, take one final parting shot to bring another down with you.',
  },
  {
    role: 'WITCH',
    name: 'Witch',
    team: 'VILLAGERS',
    icon: Sparkles,
    color: 'text-pink-600 dark:text-pink-400',
    badgeClass: 'bg-pink-50 dark:bg-pink-950/70 text-pink-700 dark:text-pink-300 border-pink-200 dark:border-pink-800/80',
    description: 'Wakes up after wolves attack to see the victim. Has 1 Elixir of Life (save) and 1 Vial of Poison (kill).',
  },
  {
    role: 'BODYGUARD',
    name: 'Bodyguard',
    team: 'VILLAGERS',
    icon: Shield,
    color: 'text-cyan-600 dark:text-cyan-400',
    badgeClass: 'bg-cyan-50 dark:bg-cyan-950/70 text-cyan-700 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800/80',
    description: 'Each night, choose one other player to stand guard over.',
  },
  {
    role: 'CUPID',
    name: 'Cupid',
    team: 'VILLAGERS',
    icon: Heart,
    color: 'text-rose-600 dark:text-rose-400',
    badgeClass: 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
    description: 'On Night 1, bind two players as Lovers. If one dies, the other perishes of heartbreak.',
  },
  {
    role: 'LITTLE_GIRL',
    name: 'Little Girl',
    team: 'VILLAGERS',
    icon: EyeOff,
    color: 'text-fuchsia-600 dark:text-fuchsia-400',
    badgeClass: 'bg-fuchsia-50 dark:bg-fuchsia-950/70 text-fuchsia-700 dark:text-fuchsia-300 border-fuchsia-200 dark:border-fuchsia-800/80',
    description: 'Can peek through the shadows at night to spy on the Werewolves, but risks being caught!',
  },
  {
    role: 'JESTER',
    name: 'Jester',
    team: 'JESTER',
    icon: Laugh,
    color: 'text-amber-600 dark:text-amber-400',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
    description: 'Wins alone immediately if the village council votes to execute them during the day!',
  },
  {
    role: 'MAYOR',
    name: 'Mayor',
    team: 'VILLAGERS',
    icon: Crown,
    color: 'text-amber-600 dark:text-amber-400',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
    description: 'Leader of the village council. Their vote counts as 2 votes in the daily voting.',
  },
  {
    role: 'THIEF',
    name: 'Thief',
    team: 'VILLAGERS',
    icon: Fingerprint,
    color: 'text-violet-600 dark:text-violet-400',
    badgeClass: 'bg-violet-50 dark:bg-violet-950/70 text-violet-700 dark:text-violet-300 border-violet-200 dark:border-violet-800/80',
    description: 'On Night 1, inspects 2 spare secret roles and can swap their role for one of them.',
  },
  {
    role: 'WOLF_CUB',
    name: 'Wolf Cub',
    team: 'WEREWOLVES',
    icon: Flame,
    color: 'text-orange-600 dark:text-orange-400',
    badgeClass: 'bg-orange-50 dark:bg-orange-950/70 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-800/80',
    description: 'Beloved pack pup. If lynched by day vote, werewolves kill TWO victims the following night.',
  },
  {
    role: 'CURSED',
    name: 'Cursed',
    team: 'VILLAGERS',
    icon: Biohazard,
    color: 'text-purple-600 dark:text-purple-400',
    badgeClass: 'bg-purple-50 dark:bg-purple-950/70 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800/80',
    description: 'Innocent villager, but if attacked by werewolves at night, transforms into a Werewolf instead of dying!',
  },
  {
    role: 'MASON',
    name: 'Mason',
    team: 'VILLAGERS',
    icon: Hammer,
    color: 'text-sky-600 dark:text-sky-400',
    badgeClass: 'bg-sky-50 dark:bg-sky-950/70 text-sky-700 dark:text-sky-300 border-sky-200 dark:border-sky-800/80',
    description: 'Recognizes all other Masons immediately on Night 1 as 100% verified innocent villagers.',
  },
  {
    role: 'LYCAN',
    name: 'Lycan',
    team: 'VILLAGERS',
    icon: PawPrint,
    color: 'text-teal-600 dark:text-teal-400',
    badgeClass: 'bg-teal-50 dark:bg-teal-950/70 text-teal-700 dark:text-teal-300 border-teal-200 dark:border-teal-800/80',
    description: 'True villager, but Seer divinations mistakenly identify them as a Werewolf.',
  },
  {
    role: 'DOPPELGANGER',
    name: 'Doppelganger',
    team: 'VILLAGERS',
    icon: Copy,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
    description: 'On Night 1, picks a player to copy. When that player dies, Doppelganger assumes their role.',
  },
  {
    role: 'WHITE_WOLF',
    name: 'White Wolf',
    team: 'WHITE_WOLF',
    icon: Swords,
    color: 'text-slate-700 dark:text-slate-300',
    badgeClass: 'bg-slate-100 dark:bg-slate-900/70 text-slate-700 dark:text-slate-300 border-slate-300 dark:border-slate-800',
    description: 'Hunts with werewolves, but every alternate (even) night can kill a werewolf. Wins alone if sole survivor.',
  },
  {
    role: 'SERIAL_KILLER',
    name: 'Serial Killer',
    team: 'SERIAL_KILLER',
    icon: Skull,
    color: 'text-rose-600 dark:text-rose-400',
    badgeClass: 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
    description: 'A deranged lone predator loyal to neither villagers nor werewolves. Kills each night. Wins only as the sole survivor.',
  },
  {
    role: 'SPELLCASTER',
    name: 'Spellcaster',
    team: 'VILLAGERS',
    icon: VolumeX,
    color: 'text-cyan-600 dark:text-cyan-400',
    badgeClass: 'bg-cyan-50 dark:bg-cyan-950/70 text-cyan-700 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800/80',
    description: 'Hexes one player with silence each night. If that player speaks in chat the next day, they are instantly struck dead!',
  },
  {
    role: 'APPRENTICE_SEER',
    name: 'Apprentice Seer',
    team: 'VILLAGERS',
    icon: Eye,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
    description: 'Acts as a normal villager until the true Seer dies, then awakens and inherits the Seer\'s divine sight.',
  },
  {
    role: 'BEAR_TAMER',
    name: 'Bear Tamer',
    team: 'VILLAGERS',
    icon: PawPrint,
    color: 'text-amber-600 dark:text-amber-400',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
    description: 'At dawn, if an adjacent living neighbor to your left or right is a Werewolf, the bear growls to alert the village.',
  },
  {
    role: 'TOUGH_GUY',
    name: 'Tough Guy',
    team: 'VILLAGERS',
    icon: HeartPulse,
    color: 'text-rose-600 dark:text-rose-400',
    badgeClass: 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
    description: 'Survives a lethal werewolf attack at night through raw grit, living through the next day and succumbing only the next night.',
  },
  {
    role: 'ARSONIST',
    name: 'Arsonist',
    team: 'ARSONIST',
    icon: Flame,
    color: 'text-orange-600 dark:text-orange-400',
    badgeClass: 'bg-orange-50 dark:bg-orange-950/70 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-800/80',
    description: 'Douses players in gasoline each night or ignites all doused victims in flames. Possesses Night Immunity against werewolf attacks!',
  },
  {
    role: 'MINION',
    name: 'Minion',
    team: 'WEREWOLVES',
    icon: VenetianMask,
    color: 'text-rose-600 dark:text-rose-400',
    badgeClass: 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-900/60',
    description: 'Devoted human servant who knows all Werewolves on Night 1. Appears innocent to the Seer. Wins with the Werewolves.',
  },
  {
    role: 'WILD_CHILD',
    name: 'Wild Child',
    team: 'VILLAGERS',
    icon: Baby,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/60',
    description: 'Selects a living Role Model on Night 1. If their Role Model dies, the Wild Child transforms into a full Werewolf!',
  },
  {
    role: 'DICTATOR',
    name: 'Dictator',
    team: 'VILLAGERS',
    icon: Gavel,
    color: 'text-amber-600 dark:text-amber-400',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/60',
    description: 'Once per game, stage a Coup to personally execute a suspect. If the victim was innocent, you commit suicide tonight from guilt.',
  },
  {
    role: 'VETERAN',
    name: 'The Veteran',
    team: 'VILLAGERS',
    icon: ShieldAlert,
    color: 'text-indigo-600 dark:text-indigo-400',
    badgeClass: 'bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/60',
    description: 'Can go on high Alert 3 times per game. While on Alert, anyone who visits or targets your house tonight is shot and killed!',
  },
  {
    role: 'AMNESIAC',
    name: 'The Amnesiac',
    team: 'NEUTRAL',
    icon: Brain,
    color: 'text-teal-600 dark:text-teal-400',
    badgeClass: 'bg-teal-50 dark:bg-teal-950/70 text-teal-700 dark:text-teal-300 border-teal-200 dark:border-teal-800/60',
    description: 'Starts with no team (Neutral). Each night, inspect all deceased players and their true roles. Once per game, choose a fallen soul to remember and permanently adopt their role and team!',
  },
];
