import { Role, RoleInfo } from './game.js';

export const ROLE_DEFINITIONS: Record<Role, RoleInfo> = {
  WEREWOLF: {
    role: 'WEREWOLF',
    name: 'Werewolf',
    team: 'WEREWOLVES',
    icon: 'Moon',
    description: 'A bloodthirsty creature lurking in human form.',
    ability: 'Each night, agree with your pack to hunt and eliminate a villager.',
    nightPriority: 50,
  },
  VILLAGER: {
    role: 'VILLAGER',
    name: 'Villager',
    team: 'VILLAGERS',
    icon: 'Users',
    description: 'An honest inhabitant of the troubled village.',
    ability: 'Use your sharp wits, deduction, and vote to ferret out the wolves before sunset.',
    nightPriority: 0,
  },
  SEER: {
    role: 'SEER',
    name: 'Seer',
    team: 'VILLAGERS',
    icon: 'Eye',
    description: 'Blessed with mystical sight to pierce mortal disguises.',
    ability: 'Each night, choose one player to peer into their soul and learn their true nature.',
    nightPriority: 10,
  },
  DOCTOR: {
    role: 'DOCTOR',
    name: 'Doctor',
    team: 'VILLAGERS',
    icon: 'HeartPulse',
    description: 'The village physician skilled in antidotes and battlefield medicine.',
    ability: 'Each night, choose one player to protect from werewolf assault.',
    nightPriority: 20,
  },
  HUNTER: {
    role: 'HUNTER',
    name: 'Hunter',
    team: 'VILLAGERS',
    icon: 'Crosshair',
    description: 'A master marksman with a hair-trigger temper.',
    ability: 'If you are slain, you may take one final shot to take another down with you.',
    nightPriority: 0,
  },
  WITCH: {
    role: 'WITCH',
    name: 'Witch',
    team: 'VILLAGERS',
    icon: 'Sparkles',
    description: 'A secretive alchemist brewing potent elixirs in the woods.',
    ability: 'Possesses one Elixir of Life to save a victim, and one Vial of Poison to eliminate someone.',
    nightPriority: 60,
  },
  BODYGUARD: {
    role: 'BODYGUARD',
    name: 'Bodyguard',
    team: 'VILLAGERS',
    icon: 'Shield',
    description: 'A stalwart warrior pledged to defend innocent lives.',
    ability: 'Each night, stand vigil over one person. They cannot be harmed tonight.',
    nightPriority: 25,
  },
};
