import { Role, RoleInfo } from './game.js';

export const ROLE_DEFINITIONS: Record<Role, RoleInfo> = {
  WEREWOLF: {
    role: 'WEREWOLF',
    name: 'Werewolf',
    team: 'WEREWOLVES',
    icon: 'Moon',
    description: 'A bloodthirsty creature lurking in human form.',
    ability: 'Each night, agree with your pack to hunt and eliminate a villager.',
    nightPriority: 50,
  },
  VILLAGER: {
    role: 'VILLAGER',
    name: 'Villager',
    team: 'VILLAGERS',
    icon: 'Users',
    description: 'An honest inhabitant of the troubled village.',
    ability: 'Use your sharp wits, deduction, and vote to ferret out the wolves before sunset.',
    nightPriority: 0,
  },
  SEER: {
    role: 'SEER',
    name: 'Seer',
    team: 'VILLAGERS',
    icon: 'Eye',
    description: 'Blessed with mystical sight to pierce mortal disguises.',
    ability: 'Each night, choose one player to peer into their soul and learn their true nature.',
    nightPriority: 10,
  },
  DOCTOR: {
    role: 'DOCTOR',
    name: 'Doctor',
    team: 'VILLAGERS',
    icon: 'HeartPulse',
    description: 'The village physician skilled in antidotes and battlefield medicine.',
    ability: 'Each night, choose one player to protect from werewolf assault.',
    nightPriority: 20,
  },
  HUNTER: {
    role: 'HUNTER',
    name: 'Hunter',
    team: 'VILLAGERS',
    icon: 'Crosshair',
    description: 'Jab tak zinda ho gaonwale ki tarah khelte ho. Marte waqt bandook se kisi ko bhi sath le ja sakte ho!',
    ability: 'Kisi bhi kaaran se eliminate (Raat me Bhediye, Witch ka zahar, ya Din me Gaonwalon ka vote) hone par marne se pehle apni bandook se kisi ek player ko goli maar kar sath le jane ka aakhri mauka milta hai.',
    nightPriority: 0,
  },
  WITCH: {
    role: 'WITCH',
    name: 'Witch',
    team: 'VILLAGERS',
    icon: 'Sparkles',
    description: 'A secretive alchemist brewing potent elixirs in the woods.',
    ability: 'Possesses one Elixir of Life to save a victim, and one Vial of Poison to eliminate someone.',
    nightPriority: 60,
  },
  BODYGUARD: {
    role: 'BODYGUARD',
    name: 'Bodyguard',
    team: 'VILLAGERS',
    icon: 'Shield',
    description: 'A stalwart warrior pledged to defend innocent lives.',
    ability: 'Each night, stand vigil over one person. They cannot be harmed tonight.',
    nightPriority: 25,
  },
  CUPID: {
    role: 'CUPID',
    name: 'Cupid',
    team: 'VILLAGERS',
    icon: 'Heart',
    description: 'The ancient archer of love.',
    ability: 'On Night 1, choose two players to become eternal Lovers. If either dies, the other dies of heartbreak.',
    nightPriority: 5,
  },
  LITTLE_GIRL: {
    role: 'LITTLE_GIRL',
    name: 'Little Girl',
    team: 'VILLAGERS',
    icon: 'EyeOff',
    description: 'A curious child wandering the shadowy forest paths.',
    ability: 'Can peek into the shadows at night to spy on werewolf identity, with a risk of being caught.',
    nightPriority: 45,
  },
  JESTER: {
    role: 'JESTER',
    name: 'Jester',
    team: 'JESTER',
    icon: 'Laugh',
    description: 'The village fool seeking the ultimate punchline.',
    ability: 'Trick the villagers into voting to hang you during the day. If executed, you win the game alone!',
    nightPriority: 0,
  },
  MAYOR: {
    role: 'MAYOR',
    name: 'Mayor',
    team: 'VILLAGERS',
    icon: 'Crown',
    description: 'The esteemed head of the village council.',
    ability: 'Your vote carries double weight (2 votes) in the daily tribunal.',
    nightPriority: 0,
  },
  THIEF: {
    role: 'THIEF',
    name: 'Thief',
    team: 'VILLAGERS',
    icon: 'Fingerprint',
    description: 'A cunning rogue looking for an identity to steal.',
    ability: 'On Night 1, inspect 2 spare hidden roles and choose one to claim as your own.',
    nightPriority: 2,
  },
  WOLF_CUB: {
    role: 'WOLF_CUB',
    name: 'Wolf Cub',
    team: 'WEREWOLVES',
    icon: 'Flame',
    description: 'The beloved newborn pup of the ravenous pack.',
    ability: 'If executed by day vote, your pack becomes enraged and slays TWO victims the next night.',
    nightPriority: 50,
  },
  CURSED: {
    role: 'CURSED',
    name: 'Cursed',
    team: 'VILLAGERS',
    icon: 'Biohazard',
    description: 'A villager bearing the dormant curse of lycanthropy.',
    ability: 'Innocent villager until attacked by werewolves—then transforms into a bloodthirsty Werewolf instead of dying.',
    nightPriority: 0,
  },
  MASON: {
    role: 'MASON',
    name: 'Mason',
    team: 'VILLAGERS',
    icon: 'Hammer',
    description: 'A brother in the secret stonemason guild.',
    ability: 'Masons recognize one another immediately on Night 1 with 100% mutual trust of innocence.',
    nightPriority: 0,
  },
  LYCAN: {
    role: 'LYCAN',
    name: 'Lycan',
    team: 'VILLAGERS',
    icon: 'PawPrint',
    description: 'A loyal villager whose blood mimics that of a wolf.',
    ability: 'You fight for the village, but the Seer divinations mistakenly perceive you as a Werewolf.',
    nightPriority: 0,
  },
  DOPPELGANGER: {
    role: 'DOPPELGANGER',
    name: 'Doppelganger',
    team: 'VILLAGERS',
    icon: 'Copy',
    description: 'A shapeshifter bound to mortal destiny.',
    ability: 'On Night 1, choose a player to mimic. When that player dies, you instantly inherit their secret role.',
    nightPriority: 3,
  },
  WHITE_WOLF: {
    role: 'WHITE_WOLF',
    name: 'White Wolf',
    team: 'WHITE_WOLF',
    icon: 'Swords',
    description: 'A solitary apex predator that belongs to no pack.',
    ability: 'Hunts disguised with the pack, but every alternate night can secretly assassinate a fellow Werewolf. Wins only as the last survivor.',
    nightPriority: 55,
  },
  SERIAL_KILLER: {
    role: 'SERIAL_KILLER',
    name: 'Serial Killer',
    team: 'SERIAL_KILLER',
    icon: 'Skull',
    description: 'A deranged lone predator loyal to neither villagers nor werewolves.',
    ability: 'Each night, choose any player to eliminate in cold blood. You win only when you are the last survivor standing.',
    nightPriority: 48,
  },
  SPELLCASTER: {
    role: 'SPELLCASTER',
    name: 'Spellcaster',
    team: 'VILLAGERS',
    icon: 'VolumeX',
    description: 'An enigmatic practitioner of silencing curses.',
    ability: 'Each night, hex one player with silence. If that player speaks in the village square the next day, they are instantly struck dead!',
    nightPriority: 15,
  },
  APPRENTICE_SEER: {
    role: 'APPRENTICE_SEER',
    name: 'Apprentice Seer',
    team: 'VILLAGERS',
    icon: 'Eye',
    description: 'A gifted student studying divination beneath the village Seer.',
    ability: 'Acts as an ordinary villager until the true Seer dies. When the Seer falls, you inherit the divine third eye from the next night onwards.',
    nightPriority: 11,
  },
  BEAR_TAMER: {
    role: 'BEAR_TAMER',
    name: 'Bear Tamer',
    team: 'VILLAGERS',
    icon: 'PawPrint',
    description: 'A woodsman accompanied by an aggressive, wolf-sniffing grizzly bear.',
    ability: 'At dawn, if any adjacent living neighbor (seated to your immediate left or right) is a Werewolf, your bear growls loudly to warn the village.',
    nightPriority: 0,
  },
  TOUGH_GUY: {
    role: 'TOUGH_GUY',
    name: 'Tough Guy',
    team: 'VILLAGERS',
    icon: 'HeartPulse',
    description: 'A resilient warrior whose immense grit withstands mortal trauma.',
    ability: 'If attacked by Werewolves at night, your sheer stamina keeps you alive through the entire following day to vote and fight, dying only the next night.',
    nightPriority: 0,
  },
  ARSONIST: {
    role: 'ARSONIST',
    name: 'Arsonist',
    team: 'ARSONIST',
    icon: 'Flame',
    description: 'A pyromaniac bent on watching the entire village burn to the ground.',
    ability: 'Each night, douse a victim in gasoline or ignite all doused players in a lethal inferno. Possesses Night Immunity against werewolf attacks!',
    nightPriority: 49,
  },
  MINION: {
    role: 'MINION',
    name: 'Minion',
    team: 'WEREWOLVES',
    icon: 'VenetianMask',
    description: 'A devoted human cultist serving the Werewolf pack from within the village.',
    ability: 'Learns the identities of all living Werewolves on Night 1 (though they do not know you). Wins whenever the Werewolves win, even if dead!',
    nightPriority: 0,
  },
  WILD_CHILD: {
    role: 'WILD_CHILD',
    name: 'Wild Child',
    team: 'VILLAGERS',
    icon: 'Baby',
    description: 'A feral youth raised among animals who idolizes a chosen villager.',
    ability: 'On Night 1, choose a living player as your Role Model. If your Role Model dies, you are consumed by grief and transform into a bloodthirsty Werewolf!',
    nightPriority: 4,
  },
  DICTATOR: {
    role: 'DICTATOR',
    name: 'Dictator',
    team: 'VILLAGERS',
    icon: 'Gavel',
    description: 'An authoritative leader capable of seizing autocratic command.',
    ability: 'Once per game during the day, stage a Coup to halt all voting and personally execute a suspect. If you execute an innocent villager, you die of guilt tonight.',
    nightPriority: 0,
  },
  VETERAN: {
    role: 'VETERAN',
    name: 'The Veteran',
    team: 'VILLAGERS',
    icon: 'ShieldAlert',
    description: 'A paranoid combat veteran guarding their homestead with deadly force.',
    ability: 'Up to 3 times per game, enter Alert mode at night. Anyone who visits or targets your house while you are on Alert is instantly shot and killed!',
    nightPriority: 8,
  },
};
