import React from 'react';
import {
  Moon,
  Users,
  Eye,
  HeartPulse,
  Crosshair,
  Sparkles,
  Shield,
  Heart,
  EyeOff,
  Laugh,
  Crown,
  Fingerprint,
  Flame,
  Biohazard,
  Hammer,
  PawPrint,
  Copy,
  Swords,
} from 'lucide-react';
import { Role, Team } from './game.js';

export interface RoleConfigMeta {
  role: Role;
  name: string;
  team: Team;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  badgeClass: string;
  description: string;
}

export const ALL_ROLES_META: RoleConfigMeta[] = [
  {
    role: 'WEREWOLF',
    name: 'Werewolf',
    team: 'WEREWOLVES',
    icon: Moon,
    color: 'text-red-400',
    badgeClass: 'bg-red-950/80 text-red-300 border-red-800/50',
    description: 'Each night, agree with your pack to hunt and eliminate a villager.',
  },
  {
    role: 'VILLAGER',
    name: 'Villager',
    team: 'VILLAGERS',
    icon: Users,
    color: 'text-blue-400',
    badgeClass: 'bg-blue-950/80 text-blue-300 border-blue-800/50',
    description: 'Use your sharp wits, deduction, and vote to ferret out the wolves before sunset.',
  },
  {
    role: 'SEER',
    name: 'Seer',
    team: 'VILLAGERS',
    icon: Eye,
    color: 'text-indigo-400',
    badgeClass: 'bg-indigo-950/80 text-indigo-300 border-indigo-800/50',
    description: 'Each night, choose one player to peer into their soul and learn their true nature.',
  },
  {
    role: 'DOCTOR',
    name: 'Doctor',
    team: 'VILLAGERS',
    icon: HeartPulse,
    color: 'text-emerald-400',
    badgeClass: 'bg-emerald-950/80 text-emerald-300 border-emerald-800/50',
    description: 'Each night, choose one player to protect from werewolf assault.',
  },
  {
    role: 'HUNTER',
    name: 'Hunter',
    team: 'VILLAGERS',
    icon: Crosshair,
    color: 'text-amber-400',
    badgeClass: 'bg-amber-950/80 text-amber-300 border-amber-800/50',
    description: 'If you are slain, take one final parting shot to bring another down with you.',
  },
  {
    role: 'WITCH',
    name: 'Witch',
    team: 'VILLAGERS',
    icon: Sparkles,
    color: 'text-pink-400',
    badgeClass: 'bg-pink-950/80 text-pink-300 border-pink-800/50',
    description: 'Wakes up after wolves attack to see the victim. Has 1 Elixir of Life (save) and 1 Vial of Poison (kill).',
  },
  {
    role: 'BODYGUARD',
    name: 'Bodyguard',
    team: 'VILLAGERS',
    icon: Shield,
    color: 'text-cyan-400',
    badgeClass: 'bg-cyan-950/80 text-cyan-300 border-cyan-800/50',
    description: 'Each night, choose one other player to stand guard over.',
  },
  {
    role: 'CUPID',
    name: 'Cupid',
    team: 'VILLAGERS',
    icon: Heart,
    color: 'text-rose-400',
    badgeClass: 'bg-rose-950/80 text-rose-300 border-rose-800/50',
    description: 'On Night 1, bind two players as Lovers. If one dies, the other perishes of heartbreak.',
  },
  {
    role: 'LITTLE_GIRL',
    name: 'Little Girl',
    team: 'VILLAGERS',
    icon: EyeOff,
    color: 'text-fuchsia-400',
    badgeClass: 'bg-fuchsia-950/80 text-fuchsia-300 border-fuchsia-800/50',
    description: 'Can peek through the shadows at night to spy on the Werewolves, but risks being caught!',
  },
  {
    role: 'JESTER',
    name: 'Jester',
    team: 'JESTER',
    icon: Laugh,
    color: 'text-yellow-400',
    badgeClass: 'bg-yellow-950/80 text-yellow-300 border-yellow-800/50',
    description: 'Wins alone immediately if the village council votes to execute them during the day!',
  },
  {
    role: 'MAYOR',
    name: 'Mayor',
    team: 'VILLAGERS',
    icon: Crown,
    color: 'text-amber-300',
    badgeClass: 'bg-amber-950/80 text-amber-200 border-amber-700/50',
    description: 'Leader of the village council. Their vote counts as 2 votes in the daily voting.',
  },
  {
    role: 'THIEF',
    name: 'Thief',
    team: 'VILLAGERS',
    icon: Fingerprint,
    color: 'text-violet-400',
    badgeClass: 'bg-violet-950/80 text-violet-300 border-violet-800/50',
    description: 'On Night 1, inspects 2 spare secret roles and can swap their role for one of them.',
  },
  {
    role: 'WOLF_CUB',
    name: 'Wolf Cub',
    team: 'WEREWOLVES',
    icon: Flame,
    color: 'text-orange-400',
    badgeClass: 'bg-orange-950/80 text-orange-300 border-orange-800/50',
    description: 'Beloved pack pup. If lynched by day vote, werewolves kill TWO victims the following night.',
  },
  {
    role: 'CURSED',
    name: 'Cursed',
    team: 'VILLAGERS',
    icon: Biohazard,
    color: 'text-purple-400',
    badgeClass: 'bg-purple-950/80 text-purple-300 border-purple-800/50',
    description: 'Innocent villager, but if attacked by werewolves at night, transforms into a Werewolf instead of dying!',
  },
  {
    role: 'MASON',
    name: 'Mason',
    team: 'VILLAGERS',
    icon: Hammer,
    color: 'text-sky-400',
    badgeClass: 'bg-sky-950/80 text-sky-300 border-sky-800/50',
    description: 'Recognizes all other Masons immediately on Night 1 as 100% verified innocent villagers.',
  },
  {
    role: 'LYCAN',
    name: 'Lycan',
    team: 'VILLAGERS',
    icon: PawPrint,
    color: 'text-teal-400',
    badgeClass: 'bg-teal-950/80 text-teal-300 border-teal-800/50',
    description: 'True villager, but Seer divinations mistakenly identify them as a Werewolf.',
  },
  {
    role: 'DOPPELGANGER',
    name: 'Doppelganger',
    team: 'VILLAGERS',
    icon: Copy,
    color: 'text-indigo-300',
    badgeClass: 'bg-indigo-950/80 text-indigo-200 border-indigo-700/50',
    description: 'On Night 1, picks a player to copy. When that player dies, Doppelganger assumes their role.',
  },
  {
    role: 'WHITE_WOLF',
    name: 'White Wolf',
    team: 'WHITE_WOLF',
    icon: Swords,
    color: 'text-slate-200',
    badgeClass: 'bg-slate-900 text-slate-100 border-slate-700',
    description: 'Hunts with werewolves, but every alternate (even) night can kill a werewolf. Wins alone if sole survivor.',
  },
];
