import { Role, RoleInfo } from './game.js';

export const ROLE_DEFINITIONS: Record<Role, RoleInfo> = {
  WEREWOLF: {
    role: 'WEREWOLF',
    name: 'Werewolf',
    team: 'WEREWOLVES',
    icon: 'Moon',
    description: 'A bloodthirsty creature lurking in human form.',
    ability: 'Each night, agree with your pack to hunt and eliminate a villager.',
    nightPriority: 50,
  },
  VILLAGER: {
    role: 'VILLAGER',
    name: 'Villager',
    team: 'VILLAGERS',
    icon: 'Users',
    description: 'An honest inhabitant of the troubled village.',
    ability: 'Use your sharp wits, deduction, and vote to ferret out the wolves before sunset.',
    nightPriority: 0,
  },
  SEER: {
    role: 'SEER',
    name: 'Seer',
    team: 'VILLAGERS',
    icon: 'Eye',
    description: 'Blessed with mystical sight to pierce mortal disguises.',
    ability: 'Each night, choose one player to peer into their soul and learn their true nature.',
    nightPriority: 10,
  },
  DOCTOR: {
    role: 'DOCTOR',
    name: 'Doctor',
    team: 'VILLAGERS',
    icon: 'HeartPulse',
    description: 'The village physician skilled in antidotes and battlefield medicine.',
    ability: 'Each night, choose one player to protect from werewolf assault.',
    nightPriority: 20,
  },
  HUNTER: {
    role: 'HUNTER',
    name: 'Hunter',
    team: 'VILLAGERS',
    icon: 'Crosshair',
    description: 'Jab tak zinda ho gaonwale ki tarah khelte ho. Marte waqt bandook se kisi ko bhi sath le ja sakte ho!',
    ability: 'Kisi bhi kaaran se eliminate (Raat me Bhediye, Witch ka zahar, ya Din me Gaonwalon ka vote) hone par marne se pehle apni bandook se kisi ek player ko goli maar kar sath le jane ka aakhri mauka milta hai.',
    nightPriority: 0,
  },
  WITCH: {
    role: 'WITCH',
    name: 'Witch',
    team: 'VILLAGERS',
    icon: 'Sparkles',
    description: 'A secretive alchemist brewing potent elixirs in the woods.',
    ability: 'Possesses one Elixir of Life to save a victim, and one Vial of Poison to eliminate someone.',
    nightPriority: 60,
  },
  BODYGUARD: {
    role: 'BODYGUARD',
    name: 'Bodyguard',
    team: 'VILLAGERS',
    icon: 'Shield',
    description: 'A stalwart warrior pledged to defend innocent lives.',
    ability: 'Each night, stand vigil over one person. They cannot be harmed tonight.',
    nightPriority: 25,
  },
  CUPID: {
    role: 'CUPID',
    name: 'Cupid',
    team: 'VILLAGERS',
    icon: 'Heart',
    description: 'The ancient archer of love.',
    ability: 'On Night 1, choose two players to become eternal Lovers. If either dies, the other dies of heartbreak.',
    nightPriority: 5,
  },
  LITTLE_GIRL: {
    role: 'LITTLE_GIRL',
    name: 'Little Girl',
    team: 'VILLAGERS',
    icon: 'EyeOff',
    description: 'A curious child wandering the shadowy forest paths.',
    ability: 'Can peek into the shadows at night to spy on werewolf identity, with a risk of being caught.',
    nightPriority: 45,
  },
  JESTER: {
    role: 'JESTER',
    name: 'Jester',
    team: 'JESTER',
    icon: 'Laugh',
    description: 'The village fool seeking the ultimate punchline.',
    ability: 'Trick the villagers into voting to hang you during the day. If executed, you win the game alone!',
    nightPriority: 0,
  },
  MAYOR: {
    role: 'MAYOR',
    name: 'Mayor',
    team: 'VILLAGERS',
    icon: 'Crown',
    description: 'The esteemed head of the village council.',
    ability: 'Your vote carries double weight (2 votes) in the daily tribunal.',
    nightPriority: 0,
  },
  THIEF: {
    role: 'THIEF',
    name: 'Thief',
    team: 'VILLAGERS',
    icon: 'Fingerprint',
    description: 'A cunning rogue looking for an identity to steal.',
    ability: 'On Night 1, inspect 2 spare hidden roles and choose one to claim as your own.',
    nightPriority: 2,
  },
  WOLF_CUB: {
    role: 'WOLF_CUB',
    name: 'Wolf Cub',
    team: 'WEREWOLVES',
    icon: 'Flame',
    description: 'The beloved newborn pup of the ravenous pack.',
    ability: 'If executed by day vote, your pack becomes enraged and slays TWO victims the next night.',
    nightPriority: 50,
  },
  CURSED: {
    role: 'CURSED',
    name: 'Cursed',
    team: 'VILLAGERS',
    icon: 'Biohazard',
    description: 'A villager bearing the dormant curse of lycanthropy.',
    ability: 'Innocent villager until attacked by werewolves—then transforms into a bloodthirsty Werewolf instead of dying.',
    nightPriority: 0,
  },
  MASON: {
    role: 'MASON',
    name: 'Mason',
    team: 'VILLAGERS',
    icon: 'Hammer',
    description: 'A brother in the secret stonemason guild.',
    ability: 'Masons recognize one another immediately on Night 1 with 100% mutual trust of innocence.',
    nightPriority: 0,
  },
  LYCAN: {
    role: 'LYCAN',
    name: 'Lycan',
    team: 'VILLAGERS',
    icon: 'PawPrint',
    description: 'A loyal villager whose blood mimics that of a wolf.',
    ability: 'You fight for the village, but the Seer divinations mistakenly perceive you as a Werewolf.',
    nightPriority: 0,
  },
  DOPPELGANGER: {
    role: 'DOPPELGANGER',
    name: 'Doppelganger',
    team: 'VILLAGERS',
    icon: 'Copy',
    description: 'A shapeshifter bound to mortal destiny.',
    ability: 'On Night 1, choose a player to mimic. When that player dies, you instantly inherit their secret role.',
    nightPriority: 3,
  },
  WHITE_WOLF: {
    role: 'WHITE_WOLF',
    name: 'White Wolf',
    team: 'WHITE_WOLF',
    icon: 'Swords',
    description: 'A solitary apex predator that obeys no master.',
    ability: 'Hunts with the pack, but every even night can secretly kill another Werewolf. Wins alone.',
    nightPriority: 55,
  },
};
